CVGEN/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('core.urls')),
    path('cv/', include('pdfgen.urls')),
    path('users/', include('user.urls')),
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import ProfileAPIView, SkillViewSet, UserEducationViewSet, UserJobViewSet, UserProjectViewSet, UserSkillViewSet

router = DefaultRouter()
router.register('skills', SkillViewSet, basename='skill-viewset')
router.register('my_skills', UserSkillViewSet, basename='userskill-viewset')
router.register('education', UserEducationViewSet, basename='usereducation-viewset')
router.register('jobs', UserJobViewSet, basename='userjob-viewset')
router.register('projects', UserProjectViewSet, basename='userproject-viewset')


urlpatterns = [
    path('profile/', ProfileAPIView.as_view()),
] + router.urls

pdfgen/urls.py
from django.urls import path
from .views import cvgen, test

urlpatterns = [
    path('resume/', cvgen.as_view()),
    path('pdf/', test.as_view()),
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.forms import CharField, DurationField
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(to=get_user_model(), on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profiles/', default='profiles/no-profile.png')
    phone_number = models.CharField(max_length=13, blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    is_employed = models.BooleanField(default=False)
    company = models.CharField(max_length=100, blank=True, null=True)
    job_title = models.CharField(max_length=75, blank=True, null=True)
    bio = models.CharField(max_length=250, blank=True, null=True)


class Skill(models.Model):
    
    name = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return self.name


class UserSkill(models.Model):

    LEVEL_CHOICES = [
        (1, 'Beginner'),
        (2, 'Advanced Beginner'),
        (3, 'Competent'),
        (4, 'Proficient'),
        (5, 'Expert')
    ]

    user = models.ForeignKey(to=get_user_model(), on_delete=models.CASCADE)
    skill = models.ForeignKey(to=Skill, on_delete=models.CASCADE)
    level = models.PositiveSmallIntegerField(choices=LEVEL_CHOICES, default=1)


class UserEducation(models.Model):

    DEGREE_CHOICES = [
        ('HS', 'Highschool Student'),
        ('DP', 'Diploma'),
        ('CS', 'College Student'),
        ('BS', 'Bachelor of Science'),
        ('MS', 'Masters of Science'),
        ('DR', 'Doctrate')
    ]

    user = models.ForeignKey(to=get_user_model(), on_delete=models.CASCADE)
    degree = models.CharField(max_length=2, choices=DEGREE_CHOICES)
    field = models.CharField(max_length=150)
    educational_center = models.CharField(max_length=150)
    start_year = models.PositiveSmallIntegerField(null=True)
    finish_year = models.PositiveSmallIntegerField(blank=True, null=True)
    still_going = models.BooleanField(default=False)
    description = models.CharField(max_length=200, blank=True)


class UserJob(models.Model):

    user = models.ForeignKey(to=get_user_model(), on_delete=models.CASCADE)
    position = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    start_year = models.PositiveSmallIntegerField(null=True)
    finish_year = models.PositiveSmallIntegerField(blank=True, null=True)
    still_going = models.BooleanField(default=False)
    description = models.CharField(max_length=200, blank=True)
    

class UserProject(models.Model):
    user = models.ForeignKey(to=get_user_model(), on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    url = models.URLField(blank=True, null=True)
    description = models.CharField(max_length=200, blank=True)

pdfgen/models.py
from django.db import models

# Create your models here.

pdfgen/views.py
from django.shortcuts import render
from datetime import datetime   
from io import StringIO
from xhtml2pdf import pisa
from django.template.loader import get_template
from django.template import Context
from django.http import HttpResponse
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework import status

from core.models import Profile, UserEducation, UserProject, UserJob, UserSkill


class cvgen(APIView):
    
    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
       
        user = self.request.user
        
        context = {}
        context['user'] = user
        context['profile'] = Profile.objects.get(user=user)
        context['educations'] = UserEducation.objects.filter(user=user).order_by('-start_year').all()
        context['projects'] = UserProject.objects.filter(user=user).all()
        context['jobs'] = UserJob.objects.filter(user=user).order_by('-start_year').all()
        context['skills'] = UserSkill.objects.filter(user=user).all()
        return render(request, 'srt-resume.html', context=context)

class test(APIView):

    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        user = request.user

        template_path = 'srt-resume.html'
        
        context = {}
        context['user'] = user
        context['profile'] = Profile.objects.get(user=user)
        context['educations'] = UserEducation.objects.filter(user=user).order_by('-start_year').all()
        context['projects'] = UserProject.objects.filter(user=user).all()
        context['jobs'] = UserJob.objects.filter(user=user).order_by('-start_year').all()
        context['skills'] = UserSkill.objects.filter(user=user).all()

        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = f'filename="resume{str(datetime.now().date())}"'

        template = get_template(template_path)
        html = template.render(context)

        pisa_status = pisa.CreatePDF(html, dest=response)

        if pisa_status.err:
            return HttpResponse({'detail': 'Something went wrong!'}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

        return response

pdfgen/templates/srt-resume.html
<!DOCTYPE html >
<html>
{% load static %}
<head>

	<title>resume-{{user.first_name}} {{user.last_name}} </title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />

	<meta name="keywords" content="" />
	<meta name="description" content="" />

	<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/reset-fonts-grids.css' %}" media="all" />
	<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/resume.css' %}" media="all" />

	<style>
		html{
    color:#000;
    background:#FFF;
}
body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,button,textarea,p,blockquote,th,td{
    margin:0;
    padding:0;
}
table{
    border-collapse:collapse;
    border-spacing:0;
}
fieldset,img{
    border:0;
}
address,caption,cite,code,dfn,em,strong,th,var,optgroup{
    font-style:inherit;
    font-weight:inherit;
}
del,ins{
    text-decoration:none;
}
li{
    list-style:none;
}
caption,th{
    text-align:left;
}
h1,h2,h3,h4,h5,h6{
    font-size:100%;
    font-weight:normal;
}
q:before,q:after{
    content:'';
}
abbr,acronym{
    border:0;
    font-variant:normal;
}
sup{
    vertical-align:baseline;
}
sub{
    vertical-align:baseline;
}
legend{
    color:#000;
}
input,button,textarea,select,optgroup,option{
    font-family:inherit;
    font-size:inherit;
    font-style:inherit;
    font-weight:inherit;
}
input,button,textarea,select{
    *font-size:100%;
}
body{
    font:13px/1.231 arial,helvetica,clean,sans-serif;
    *font-size:small;
    *font:x-small;
}
select,input,button,textarea,button{
    font:99% arial,helvetica,clean,sans-serif;
}
table{
    font-size:inherit;
    font:100%;
}
pre,code,kbd,samp,tt{
    font-family:monospace;
    *font-size:108%;
    line-height:100%;
}
body{
    text-align:center;
}
#doc,#doc2,#doc3,#doc4,.yui-t1,.yui-t2,.yui-t3,.yui-t4,.yui-t5,.yui-t6,.yui-t7{
    margin:auto;
    text-align:left;
    width:57.69em;
    *width:56.25em;
}
#doc2{
    width:73.076em;
    *width:71.25em;
}
#doc3{
    margin:auto 10px;
    width:auto;
}
#doc4{
    width:74.923em;
    *width:73.05em;
}
.yui-b{
    position:relative;
}
.yui-b{
    _position:static;
}
#yui-main .yui-b{
    position:static;
}
#yui-main,.yui-g .yui-u .yui-g{
    width:100%;
}
.yui-t1 #yui-main,.yui-t2 #yui-main,.yui-t3 #yui-main{
    float:right;
    margin-left:-25em;
}
.yui-t4 #yui-main,.yui-t5 #yui-main,.yui-t6 #yui-main{
    float:left;
    margin-right:-25em;
}
.yui-t1 .yui-b{
    float:left;
    width:12.30769em;
    *width:12.00em;
}
.yui-t1 #yui-main .yui-b{
    margin-left:13.30769em;
    *margin-left:13.05em;
}
.yui-t2 .yui-b{
    float:left;
    width:13.8461em;
    *width:13.50em;
}
.yui-t2 #yui-main .yui-b{
    margin-left:14.8461em;
    *margin-left:14.55em;
}
.yui-t3 .yui-b{
    float:left;
    width:23.0769em;
    *width:22.50em;
}
.yui-t3 #yui-main .yui-b{
    margin-left:24.0769em;
    *margin-left:23.62em;
}
.yui-t4 .yui-b{
    float:right;
    width:13.8456em;
    *width:13.50em;
}
.yui-t4 #yui-main .yui-b{
    margin-right:14.8456em;
    *margin-right:14.55em;
}
.yui-t5 .yui-b{
    float:right;
    width:18.4615em;
    *width:18.00em;
}
.yui-t5 #yui-main .yui-b{
    margin-right:19.4615em;
    *margin-right:19.125em;
}
.yui-t6 .yui-b{
    float:right;
    width:23.0769em;
    *width:22.50em;
}
.yui-t6 #yui-main .yui-b{
    margin-right:24.0769em;
    *margin-right:23.62em;
}
.yui-t7 #yui-main .yui-b{
    display:block;
    margin:0 0 1em 0;
}
#yui-main .yui-b{
    float:none;
    width:auto;
}
.yui-gb .yui-u,.yui-g .yui-gb .yui-u,.yui-gb .yui-g,.yui-gb .yui-gb,.yui-gb .yui-gc,.yui-gb .yui-gd,.yui-gb .yui-ge,.yui-gb .yui-gf,.yui-gc .yui-u,.yui-gc .yui-g,.yui-gd .yui-u{
    float:left;
}
.yui-g .yui-u,.yui-g .yui-g,.yui-g .yui-gb,.yui-g .yui-gc,.yui-g .yui-gd,.yui-g .yui-ge,.yui-g .yui-gf,.yui-gc .yui-u,.yui-gd .yui-g,.yui-g .yui-gc .yui-u,.yui-ge .yui-u,.yui-ge .yui-g,.yui-gf .yui-g,.yui-gf .yui-u{
    float:right;
}
.yui-g div.first,.yui-gb div.first,.yui-gc div.first,.yui-gd div.first,.yui-ge div.first,.yui-gf div.first,.yui-g .yui-gc div.first,.yui-g .yui-ge div.first,.yui-gc div.first div.first{
    float:left;
}
.yui-g .yui-u,.yui-g .yui-g,.yui-g .yui-gb,.yui-g .yui-gc,.yui-g .yui-gd,.yui-g .yui-ge,.yui-g .yui-gf{
    width:49.1%;
}
.yui-gb .yui-u,.yui-g .yui-gb .yui-u,.yui-gb .yui-g,.yui-gb .yui-gb,.yui-gb .yui-gc,.yui-gb .yui-gd,.yui-gb .yui-ge,.yui-gb .yui-gf,.yui-gc .yui-u,.yui-gc .yui-g,.yui-gd .yui-u{
    width:32%;
    margin-left:1.99%;
}
.yui-gb .yui-u{
    *margin-left:1.9%;
    *width:31.9%;
}
.yui-gc div.first,.yui-gd .yui-u{
    width:66%;
}
.yui-gd div.first{
    width:32%;
}
.yui-ge div.first,.yui-gf .yui-u{
    width:74.2%;
}
.yui-ge .yui-u,.yui-gf div.first{
    width:24%;
}
.yui-g .yui-gb div.first,.yui-gb div.first,.yui-gc div.first,.yui-gd div.first{
    margin-left:0;
}
.yui-g .yui-g .yui-u,.yui-gb .yui-g .yui-u,.yui-gc .yui-g .yui-u,.yui-gd .yui-g .yui-u,.yui-ge .yui-g .yui-u,.yui-gf .yui-g .yui-u{
    width:49%;
    *width:48.1%;
    *margin-left:0;
}
.yui-g .yui-g .yui-u{
    width:48.1%;
}
.yui-g .yui-gb div.first,.yui-gb .yui-gb div.first{
    *margin-right:0;
    *width:32%;
    _width:31.7%;
}
.yui-g .yui-gc div.first,.yui-gd .yui-g{
    width:66%;
}
.yui-gb .yui-g div.first{
    *margin-right:4%;
    _margin-right:1.3%;
}
.yui-gb .yui-gc div.first,.yui-gb .yui-gd div.first{
    *margin-right:0;
}
.yui-gb .yui-gb .yui-u,.yui-gb .yui-gc .yui-u{
    *margin-left:1.8%;
    _margin-left:4%;
}
.yui-g .yui-gb .yui-u{
    _margin-left:1.0%;
}
.yui-gb .yui-gd .yui-u{
    *width:66%;
    _width:61.2%;
}
.yui-gb .yui-gd div.first{
    *width:31%;
    _width:29.5%;
}
.yui-g .yui-gc .yui-u,.yui-gb .yui-gc .yui-u{
    width:32%;
    _float:right;
    margin-right:0;
    _margin-left:0;
}
.yui-gb .yui-gc div.first{
    width:66%;
    *float:left;
    *margin-left:0;
}
.yui-gb .yui-ge .yui-u,.yui-gb .yui-gf .yui-u{
    margin:0;
}
.yui-gb .yui-gb .yui-u{
    _margin-left:.7%;
}
.yui-gb .yui-g div.first,.yui-gb .yui-gb div.first{
    *margin-left:0;
}
.yui-gc .yui-g .yui-u,.yui-gd .yui-g .yui-u{
    *width:48.1%;
    *margin-left:0;
}
.yui-gb .yui-gd div.first{
    width:32%;
}
.yui-g .yui-gd div.first{
    _width:29.9%;
}
.yui-ge .yui-g{
    width:24%;
}
.yui-gf .yui-g{
    width:74.2%;
}
.yui-gb .yui-ge div.yui-u,.yui-gb .yui-gf div.yui-u{
    float:right;
}
.yui-gb .yui-ge div.first,.yui-gb .yui-gf div.first{
    float:left;
}
.yui-gb .yui-ge .yui-u,.yui-gb .yui-gf div.first{
    *width:24%;
    _width:20%;
}
.yui-gb .yui-ge div.first,.yui-gb .yui-gf .yui-u{
    *width:73.5%;
    _width:65.5%;
}
.yui-ge div.first .yui-gd .yui-u{
    width:65%;
}
.yui-ge div.first .yui-gd div.first{
    width:32%;
}
#hd:after,#bd:after,#ft:after,.yui-g:after,.yui-gb:after,.yui-gc:after,.yui-gd:after,.yui-ge:after,.yui-gf:after{
    content:".";
    display:block;
    height:0;
    clear:both;
    visibility:hidden;
}
#hd,#bd,#ft,.yui-g,.yui-gb,.yui-gc,.yui-gd,.yui-ge,.yui-gf{
    zoom:1;
}

.msg { padding: 10px; background: #222; position: relative; }
.msg h1 { color: #fff;  }
.msg a { margin-left: 20px; background: #408814; color: white; padding: 4px 8px; text-decoration: none; }
.msg a:hover { background: #266400; }

/* //-- yui-grids style overrides -- */
body { font-family: Georgia; color: #444; }
#inner { padding: 10px 80px; margin: 80px auto; background: #f5f5f5; border: solid #666; border-width: 8px 0 2px 0; }
.yui-gf { margin-bottom: 2em; padding-bottom: 2em; border-bottom: 1px solid #ccc; }

/* //-- header, body, footer -- */
#hd { margin: 2.5em 0 3em 0; padding-bottom: 1.5em; border-bottom: 1px solid #ccc }
#hd h2 { text-transform: uppercase; letter-spacing: 2px; }
#bd, #ft { margin-bottom: 2em; }

/* //-- footer -- */
#ft { padding: 1em 0 5em 0; font-size: 92%; border-top: 1px solid #ccc; text-align: center; }
#ft p { margin-bottom: 0; text-align: center;   }

/* //-- core typography and style -- */
#hd h1 { font-size: 48px; text-transform: uppercase; letter-spacing: 3px; }
h2 { font-size: 152% }
h3, h4 { font-size: 122%; }
h1, h2, h3, h4 { color: #333; }
p { font-size: 100%; line-height: 18px; padding-right: 3em; }
a { color: #990003 }
a:hover { text-decoration: none; }
strong { font-weight: bold; }
li { line-height: 24px; border-bottom: 1px solid #ccc; }
p.enlarge { font-size: 144%; padding-right: 6.5em; line-height: 24px; }
p.enlarge span { color: #000 }
.contact-info { margin-top: 7px; }
.first h2 { font-style: italic; }
.last { border-bottom: 0 }


/* //-- section styles -- */

a#pdf { display: block; float: left; background: #666; color: white; padding: 6px 50px 6px 12px; margin-bottom: 6px; text-decoration: none;  }
a#pdf:hover { background: #222; }

.job { position: relative; margin-bottom: 1em; padding-bottom: 1em; border-bottom: 1px solid #ccc; }
.job h4 { position: absolute; top: 0.35em; right: 0 }
.job p { margin: 0.75em 0 3em 0; }

.last { border: none; }

.skills-list ul { margin: 0; }
.skills-list li { margin: 3px 0; padding: 3px 0; }
.skills-list li span { font-size: 152%; display: block; margin-bottom: -2px; padding: 0 }
.talent { width: 32%; float: left;}
.talent h2 { margin-bottom: 6px; }

#srt-ttab { margin-bottom: 100px; text-align: center;  }
#srt-ttab img.last { margin-top: 20px }

/* --// override to force 1/8th width grids -- */
.yui-gf .yui-u{width:80.2%;}
.yui-gf div.first{width:12.3%;}


#profile-image{
    width: 200px;
    height: 200px;
    border-radius: 10px;
}

.edu{
    margin-bottom: 20px;
}

.proj-url{
    text-decoration: none;
    color: #333;
}

	</style>

</head>
<body>

<div id="doc2" class="yui-t7">
	<div id="inner">
	
		<div id="hd">
			<div class="yui-gc">
				<div class="yui-u first">
					<h1>{{user.first_name}} {{user.last_name}}</h1>
					<h2>{{profile.job_title}}</h2>
				</div>

				<div class="yui-u">
					<div class="contact-info">
						<img id="profile-image" src={{ profile.image.url }}>
						<h3>email: <a href="mailto:{{user.email}}">{{user.email}}</a></h3>
						<h3>phone: {{profile.phone_number}}</h3>
						<h3>location: {{profile.location}}</h3>
					</div><!--// .contact-info -->
				</div>
			</div><!--// .yui-gc -->
		</div><!--// hd -->

		<div id="bd">
			<div id="yui-main">
				<div class="yui-b">

					<div class="yui-gf">
						<div class="yui-u first">
							<h2>Profile</h2>
						</div>
						<div class="yui-u">
							<p class="enlarge">
								{{profile.bio}}
							</p>
						</div>
					</div><!--// .yui-gf -->

					<div class="yui-gf">
						<div class="yui-u first">
							<h2>Skills</h2>
						</div>
						<div class="yui-u">
								{% for skill in skills %}
								<div class="talent">
									<h2>{{skill.skill}}</h2>
									<p>{{skill.get_level_display}}</p>
								</div>
								{% endfor %}
								
						</div>
					</div><!--// .yui-gf -->

					

					<div class="yui-gf">
	
						<div class="yui-u first">
							<h2>Experience</h2>
						</div><!--// .yui-u -->

						<div class="yui-u">
							{% for job in jobs %}
							<div class="job">
								<h2>{{ job.company }}</h2>
								<h3>{{ job.position }}</h3>
								{% if job.still_going %}
								<h4>{{ job.start_year }}-Now</h4>
								{% else %}
								<h4>{{ job.start_year }}-{{job.finish_year}}</h4>
								{% endif %}

								<p>{{job.description}}</p>
							</div>
							{% endfor %}
						</div><!--// .yui-u -->
					</div><!--// .yui-gf -->


					<div class="yui-gf ">
						<div class="yui-u first">
							<h2>Education</h2>
						</div>
						{% for education in educations %}
						<div class="yui-u edu">
							<h2><strong>{{education.field}} </strong> - {{education.educational_center}}</h2>
							<h3>{{education.get_degree_display}} </h3>
						</div>
						{% endfor %}
					</div><!--// .yui-gf -->


					<div class="yui-gf last">
	
						<div class="yui-u first">
							<h2>Projects</h2>
						</div><!--// .yui-u -->

						<div class="yui-u">
							{% for proj in projects %}
							<div class="job">
								<h2><a class="proj-url" href={{proj.url}}>{{proj.name }}</a> </h2>
								<h3>{{ proj.description }}</h3>
								
								
								
							</div>
							{% endfor %}
						</div><!--// .yui-u -->
					</div><!--// .yui-gf -->



				</div><!--// .yui-b -->
			</div><!--// yui-main -->
		</div><!--// bd -->

		<div id="ft">
			<p>CVGEN &mdash; <a href="https://github.com/miirzamiir/cvgen">github repo</a></p>
		</div><!--// footer -->

	</div><!-- // inner -->


</div><!--// doc -->


</body>
</html>